            <hr style="clear:both">
            <footer>
                <p><a
                    href="https://week03.atlassian.net/?continue=https%3A%2F%2Fweek03.atlassian.net%2Fwelcome%2Fsoftware%3FprojectId%3D10000&atlOrigin=eyJpIjoiMDAxNWY0ZDYxZmMwNDg2NmJkYjcwYjdlNWU5ZWMwMWQiLCJwIjoiamlyYS1zb2Z0d2FyZSJ9">
                    Jira Space
                    <img class="icon icon-light-mode" src="<?php echo($prefix);?>/images/icons/jira-icon-light.png" alt="">
                    <img class="icon icon-dark-mode" src="<?php echo($prefix);?>/images/icons/jira-icon-dark.png" alt="">
                </a></p>
                <p><a href="https://github.com/106429465/razeen-thurs-230-g01">GitHub Repository
                    <img class="icon icon-light-mode" src="<?php echo($prefix);?>/images/icons/github-icon-light.png" alt="">
                    <img class="icon icon-dark-mode" src="<?php echo($prefix);?>/images/icons/github-icon-dark.png" alt="">
                </a></p>
                <p><a href="https://healthml.site">Site URL
                    <img class="icon icon-light-mode" src="<?php echo($prefix);?>/images/icons/website-icon-light.png" alt="">
                    <img class="icon icon-dark-mode" src="<?php echo($prefix);?>/images/icons/website-icon-dark.png" alt="">
                </a></p>
                <p><a href="mailto:admin@healthml.site">Company Email
                    <img class="icon icon-light-mode" src="<?php echo($prefix);?>/images/icons/email-icon-light.png" alt="">
                    <img class="icon icon-dark-mode" src="<?php echo($prefix);?>/images/icons/email-icon-dark.png" alt="">
                </a></p>
            </footer>
        </div>
    </body>

</html>
