            <hr style="clear:both">
            <footer>
                <p><a href="https://github.com/106429465/razeen-thurs-230-g01-part2">GitHub Repository
                    <img class="icon icon-light-mode" src="<?php echo($prefix);?>/images/icons/github-icon-light.png" alt="">
                    <img class="icon icon-dark-mode" src="<?php echo($prefix);?>/images/icons/github-icon-dark.png" alt="">
                </a></p>
                <p><a href="https://healthml.site">Site URL
                    <img class="icon icon-light-mode" src="<?php echo($prefix);?>/images/icons/website-icon-light.png" alt="">
                    <img class="icon icon-dark-mode" src="<?php echo($prefix);?>/images/icons/website-icon-dark.png" alt="">
                </a></p>
                <p><a href="mailto:admin@healthml.site">Company Email
                    <img class="icon icon-light-mode" src="<?php echo($prefix);?>/images/icons/email-icon-light.png" alt="">
                    <img class="icon icon-dark-mode" src="<?php echo($prefix);?>/images/icons/email-icon-dark.png" alt="">
                </a></p>
            </footer>
        </div>
    </body>

</html>
