<nav id="nav-light" class='nav-style'>
        <ul>
          <li<?php echo($current_page == 'home' ? ' class="nav_active"' :'');?>><a href="../#light">Home<img class="icon" src="/images/icons/home-icon-light.png" alt=""></a></li>
          <li<?php echo($current_page == 'jobs' ? ' class="nav_active"' :'');?>><a href="../jobs/#light">Jobs<img class="icon" src="/images/icons/jobs-icon-light.png" alt=""></a></li>
          <li<?php echo($current_page == 'apply' ? ' class="nav_active"' :'');?>><a href="../apply/#light">Apply<img class="icon" src="/images/icons/apply-icon-light.png" alt=""></a></li>
          <li<?php echo($current_page == 'about' ? ' class="nav_active"' :'');?>><a href="../about/#light">About<img class="icon" src="/images/icons/about-icon-light.png" alt=""></a></li>
        </ul>
      </nav>
      <nav id="nav-dark" class='nav-style'>
        <ul>
          <li<?php echo($current_page == 'home' ? 'class="nav_active"' :'');?>><a href="../index.php/#dark">Home<img class="icon" src="/images/icons/home-icon-dark.png" alt=""></a></li>
          <li<?php echo($current_page == 'jobs' ? ' class="nav_active"' :'');?>><a href="../jobs/#dark">Jobs<img class="icon" src="/images/icons/jobs-icon-dark.png" alt=""></a></li>
          <li<?php echo($current_page == 'apply' ? ' class="nav_active"' :'');?>><a href="../apply/#dark">Apply<img class="icon" src="/images/icons/apply-icon-dark.png" alt=""></a></li>
          <li<?php echo($current_page == 'about' ? ' class="nav_active"' :'');?>><a href="../about/#dark">About<img class="icon" src="/images/icons/about-icon-dark.png" alt=""></a></li>
        </ul>
      </nav>